[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
axum = "0.7.9"
dotenvy = "0.15.7"
serde = "1.0.216"
tokio = { version = "1.42.0", features = ["full"] }
service = { path = "../service" }
