# compose for nextjs axum with seaorm and postgres

name: voreanation
services:
  # Frontend/ Client
  frontend:
    build:
      context: frontend
      target: final
    ports:
      - 3000:3000
    depends_on:
      - api

  # API/Server
  api:
    build:
      context: backend
    depends_on:
      db:
        condition: service_healthy

  # Database: postgres
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - voreanation-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=voreanation
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  voreanation-db:
