# compose for nextjs axum with seaorm and postgres

name: voreanation
services:
  # Frontend/ Client
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  # API/Server
  api:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  # Database: postgres
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - voreanation-db:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    expose:
      - 5432
    ports:
      - "5432:5432"
volumes:
  voreanation-db:
